# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 cave-home contributors

include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: false
    require_trailing_commas: true
